In [1]:
import numpy as np



# Создание случайной матрицы из 1000 строк и 50 столбцов

In [4]:
X = np.random.normal(loc=1, scale=100, size=(1000, 50))

In [5]:
print(X)

[[  76.66499551   98.14099974  163.52411674 ...  -99.94988285
    99.38219324 -116.79502189]
 [-198.67575134  -30.22109832 -150.9917805  ...   92.12149786
   105.41653295 -105.59721126]
 [-155.67688813   80.51926427  -30.18691152 ...  -88.80187722
   -16.50668075  -55.96696397]
 ...
 [  61.16061141  -82.79357942   94.35939773 ...    0.91866237
    48.41391073  200.06126291]
 [-103.3635268   -59.32107531 -162.76912963 ...  -57.20863083
   -52.04964442   32.69416575]
 [  92.64925471   -0.24102235  -54.97992891 ...  -16.43569917
   148.94905332  -40.12576454]]


# Нормирование матрицы по столбцам

In [8]:
m = np.mean(X, axis=0)

In [9]:
s = np.std(X, axis=0)

In [12]:
X_norm = (X - m) / s

In [13]:
print(X)

[[ 0.71992424  1.03455657  1.64677545 ... -1.0800225   0.94890651
  -1.18561532]
 [-2.01841715 -0.305723   -1.5015654  ...  0.90257111  1.0079059
  -1.07106339]
 [-1.59078133  0.85056104 -0.29229456 ... -0.96495089 -0.18417067
  -0.56335339]
 ...
 [ 0.56572877 -0.85465313  0.95442854 ... -0.03884014  0.45057569
   2.05577709]
 [-1.07051019 -0.60956741 -1.61945804 ... -0.63884    -0.53168393
   0.34363671]
 [ 0.87889221  0.00731086 -0.54047556 ... -0.21797483  1.43353524
  -0.40130029]]


# Выведете для матрицы номера строк, сумма которых больше 10

## Заданная матрица

In [14]:
Z = np.array ([[4, 5, 0],
              [1, 9, 3],
              [5, 1, 1],
              [3, 3, 3],
              [9, 9, 9],
              [4, 7, 1]])

## Расчет

In [16]:
sum_rows = np.sum(Z, axis=1)

In [19]:
print(np.nonzero(sum_rows > 10))

(array([1, 4, 5]),)


# Объединение матриц

In [20]:
M1 = np.eye(3)

In [21]:
M2 = np.eye(3)

In [22]:
print(np.vstack((M1, M2)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
