# 1. Загрузите данные из файла data-logistic.csv. Это двумерная выборка, целевая переменная на которой принимает значения -1 или 1

In [135]:
import pandas as pd


data = pd.read_csv('data-logistic.csv', header=None)

In [136]:
Y = data.values[:, :1]
X = data.values[:, 1:]

# 2. Убедитесь, что выше выписаны правильные формулы для градиентного спуска. Обратите внимание, что мы используем полноценный градиентный спуск, а не его стохастический вариант!

Проверка расчета производной подтвердила результат

# 3. Реализуйте градиентный спуск для обычной и L2-регуляризованной (с коэффициентом регуляризации 10) логистической регрессии. Используйте длину шага k=0.1. В качестве начального приближения используйте вектор (0, 0)

In [137]:
import numpy as np


def delta_w(w, k = 0.1, C = 10):
    term1 = k * (Y * X * (1 - 1 / (1 + np.exp(-Y * ((w * X).sum(axis=1, keepdims=True)))))).mean(axis=0, keepdims=True)
    term2 = -k * C * w
    return (term1 + term2)

# 4. Запустите градиентный спуск и доведите до сходимости (евклидово расстояние между векторами весов на соседних итерациях должно быть не больше 1e-5). Рекомендуется ограничить сверху число итераций десятью тысячами 

In [138]:
w = pd.DataFrame({0: [0.], 1: [0.]}).values

for i in range(10000):
    print (w)
    delta = delta_w(w)
    w += delta
    if np.linalg.norm(delta) < 10**(-5):
        print (w)
        break
w_reg = w

[[0. 0.]]
[[0.03573127 0.03245997]]
[[0.02669911 0.02275351]]
[[0.02905739 0.02532643]]
[[0.02842657 0.02463533]]
[[0.02859494 0.02481978]]
[[0.02854995 0.02477049]]
[[0.02856197 0.02478366]]
[[0.02855875 0.02478014]]


In [139]:
w = pd.DataFrame({0: [0.], 1: [0.]}).values

for i in range(10000):
    print (w)
    delta = delta_w(w, C=0)
    w += delta
    if np.linalg.norm(delta) < 10**(-5):
        print (w)
        break
w_not_reg = w

[[0. 0.]]
[[0.03573127 0.03245997]]
[[0.06243037 0.05521348]]
[[0.08343428 0.07202494]]
[[0.10067273 0.08502955]]
[[0.11522227 0.0953854 ]]
[[0.1277369  0.10377852]]
[[0.13864803 0.11065262]]
[[0.14825909 0.11631519]]
[[0.15679401 0.1209907 ]]
[[0.16442411 0.12484951]]
[[0.17128422 0.1280248 ]]
[[0.17748271 0.13062309]]
[[0.18310823 0.1327311 ]]
[[0.18823429 0.13442043]]
[[0.19292253 0.13575085]]
[[0.19722515 0.13677278]]
[[0.20118668 0.137529  ]]
[[0.20484534 0.13805607]]
[[0.20823418 0.13838541]]
[[0.21138186 0.13854411]]
[[0.21431338 0.13855564]]
[[0.21705061 0.13844037]]
[[0.21961276 0.13821605]]
[[0.22201672 0.13789816]]
[[0.22427743 0.13750023]]
[[0.2264081 0.1370341]]
[[0.22842045 0.13651015]]
[[0.2303249  0.13593747]]
[[0.23213073 0.13532406]]
[[0.23384622 0.13467691]]
[[0.23547876 0.13400218]]
[[0.23703499 0.13330526]]
[[0.23852084 0.1325909 ]]
[[0.23994164 0.13186324]]
[[0.24130219 0.13112591]]
[[0.24260681 0.1303821 ]]
[[0.24385941 0.12963459]]
[[0.2450635  0.12888581]]
[[0.

# 5. Какое значение принимает AUC-ROC на обучении без регуляризации и при ее использовании? Эти величины будут ответом на задание. В качестве ответа приведите два числа через пробел. Обратите внимание, что на вход функции roc_auc_score нужно подавать оценки вероятностей, подсчитанные обученным алгоритмом. Для этого воспользуйтесь сигмоидной функцией: a(x) = 1 / (1 + exp(-w1 x1 - w2 x2))

In [140]:
p_reg = 1 / (1 + np.exp(-(w_reg * X).sum(axis=1, keepdims=True)))
p_not_reg = 1 / (1 + np.exp(-(w_not_reg * X).sum(axis=1, keepdims=True)))

In [141]:
import sklearn.metrics as metrics


metrics.roc_auc_score(Y, p_reg)

0.9362857142857142

In [142]:
metrics.roc_auc_score(Y, p_not_reg)

0.9268571428571428

# 6. Попробуйте поменять длину шага. Будет ли сходиться алгоритм, если делать более длинные шаги? Как меняется число итераций при уменьшении длины шага?

In [143]:
w = pd.DataFrame({0: [0.], 1: [0.]}).values

for i in range(10000):
    print (w)
    delta = delta_w(w, k=0.2)
    w += delta
    if np.linalg.norm(delta) < 10**(-5):
        print (w)
        break
w_reg = w

[[0. 0.]]
[[0.07146253 0.06491994]]
[[-0.0332387  -0.03531176]]
[[0.12272516 0.11996931]]
[[-0.1019275  -0.10842148]]
[[0.21907453 0.22220609]]
[[-0.22076768 -0.23353307]]
[[0.36639488 0.37616743]]
[[-0.3912967 -0.4113688]]
[[0.56251341 0.58028771]]
[[-0.6062272 -0.6350547]]
[[0.79590341 0.82314288]]
[[-0.85164297 -0.89052836]]
[[1.05222827 1.09003891]]
[[-1.11488904 -1.16476321]]
[[1.32159906 1.3707467 ]]
[[-1.38831261 -1.44981462]]
[[1.59862825 1.65963998]]
[[-1.66787231 -1.74143579]]
[[1.88047102 1.9536966 ]]
[[-1.95140323 -2.03729953]]
[[2.16554697 2.25118561]]
[[-2.23767089 -2.33602955]]
[[2.45291929 2.55103628]]
[[-2.52592489 -2.63675087]]
[[2.74199968 2.852545  ]]
[[-2.81568356 -2.93887759]]
[[3.03240007 3.15523044]]
[[-3.10662277 -3.24200404]]
[[3.32385305 3.45875494]]
[[-3.39851507 -3.54584355]]
[[3.61616692 3.7628779 ]]
[[-3.69119472 -3.85019087]]
[[3.90919933 4.06742617]]
[[-3.98453677 -4.15489778]]
[[4.20284122 4.37227425]]
[[-4.27844428 -4.45985668]]
[[4.49700678 4.6773307

[[-60.8445599  -61.94064519]]
[[61.06605648 62.15737313]]
[[-61.14462933 -62.24425996]]
[[61.36612688 62.46098704]]
[[-61.44470067 -62.54787303]]
[[61.66619915 62.76459927]]
[[-61.74477387 -62.85148443]]
[[61.96627329 63.06820983]]
[[-62.04484891 -63.15509418]]
[[62.26634925 63.37181876]]
[[-62.34492576 -63.45870231]]
[[62.566427   63.67542609]]
[[-62.6450044  -63.76230885]]
[[62.86650652 63.97903183]]
[[-62.94508479 -64.06591381]]
[[63.16658778 64.28263602]]
[[-63.2451669  -64.36951723]]
[[63.46667075 64.58623867]]
[[-63.54525071 -64.67311913]]
[[63.76675541 64.88983981]]
[[-63.84533619 -64.97671954]]
[[64.06684172 65.19343947]]
[[-64.14542332 -65.28031847]]
[[64.36692967 65.49703766]]
[[-64.44551206 -65.58391595]]
[[64.66701922 65.80063442]]
[[-64.7456024 -65.887512 ]]
[[64.96711035 66.10422976]]
[[-65.04569431 -66.19110665]]
[[65.26720304 66.40782371]]
[[-65.34578776 -66.49469991]]
[[65.56729725 66.71141629]]
[[-65.64588272 -66.79829182]]
[[65.86739297 67.01500752]]
[[-65.94597918 -

/Users/WLMike/anaconda3/envs/ML36/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """


[[ -99.26209327 -100.79557917]]
[[ 99.48364135 101.01226087]]
[[ -99.5622645  -101.09910255]]
[[ 99.78381269 101.31578415]]
[[ -99.86243595 -101.40262573]]
[[100.08398424 101.61930723]]
[[-100.16260761 -101.70614872]]
[[100.38415601 101.92283013]]
[[-100.46277948 -102.00967152]]
[[100.68432798 102.22635283]]
[[-100.76295155 -102.31319414]]
[[100.98450016 102.52987536]]
[[-101.06312383 -102.61671657]]
[[101.28467254 102.8333977 ]]
[[-101.36329631 -102.92023882]]
[[101.58484511 103.13691987]]
[[-101.66346898 -103.2237609 ]]
[[101.88501788 103.44044186]]
[[-101.96364184 -103.52728281]]
[[102.18519084 103.74396368]]
[[-102.26381489 -103.83080455]]
[[102.48536398 104.04748533]]
[[-102.56398812 -104.13432612]]
[[102.78553731 104.35100682]]
[[-102.86416154 -104.43784752]]
[[103.08571081 104.65452814]]
[[-103.16433514 -104.74136877]]
[[103.3858845  104.95804931]]
[[-103.46450891 -105.04488986]]
[[103.68605836 105.26157032]]
[[-103.76468285 -105.34841079]]
[[103.98623238 105.56509117]]
[[-104.0

[[143.60998451 145.62914033]]
[[-143.68861333 -145.7159769 ]]
[[143.91016722 145.93265336]]
[[-143.98879604 -146.01948992]]
[[144.21034994 146.23616637]]
[[-144.28897877 -146.32300293]]
[[144.51053267 146.53967937]]
[[-144.58916152 -146.62651592]]
[[144.81071542 146.84319236]]
[[-144.88934427 -146.9300289 ]]
[[145.11089819 147.14670533]]
[[-145.18952705 -147.23354187]]
[[145.41108097 147.4502183 ]]
[[-145.48970984 -147.53705482]]
[[145.71126377 147.75373124]]
[[-145.78989264 -147.84056777]]
[[146.01144658 148.05724418]]
[[-146.09007546 -148.14408069]]
[[146.3116294 148.3607571]]
[[-146.39025829 -148.44759361]]
[[146.61181224 148.66427001]]
[[-146.69044113 -148.75110651]]
[[146.91199509 148.9677829 ]]
[[-146.99062399 -149.0546194 ]]
[[147.21217796 149.27129579]]
[[-147.29080686 -149.35813228]]
[[147.51236084 149.57480866]]
[[-147.59098975 -149.66164515]]
[[147.81254373 149.87832152]]
[[-147.89117265 -149.965158  ]]
[[148.11272663 150.18183437]]
[[-148.19135556 -150.26867085]]
[[148.4129

[[-218.43428231 -221.29056269]]
[[218.65583665 221.50723874]]
[[-218.73446591 -221.5940749 ]]
[[218.95602025 221.81075096]]
[[-219.03464952 -221.89758712]]
[[219.25620385 222.11426317]]
[[-219.33483312 -222.20109934]]
[[219.55638745 222.41777539]]
[[-219.63501672 -222.50461156]]
[[219.85657106 222.72128761]]
[[-219.93520033 -222.80812378]]
[[220.15675466 223.02479983]]
[[-220.23538393 -223.11163599]]
[[220.45693826 223.32831205]]
[[-220.53556753 -223.41514821]]
[[220.75712187 223.63182426]]
[[-220.83575113 -223.71866043]]
[[221.05730547 223.93533648]]
[[-221.13593474 -224.02217265]]
[[221.35748907 224.2388487 ]]
[[-221.43611834 -224.32568486]]
[[221.65767268 224.54236092]]
[[-221.73630195 -224.62919708]]
[[221.95785628 224.84587313]]
[[-222.03648555 -224.9327093 ]]
[[222.25803989 225.14938535]]
[[-222.33666915 -225.23622151]]
[[222.55822349 225.45289757]]
[[-222.63685276 -225.53973373]]
[[222.85840709 225.75640978]]
[[-222.93703636 -225.84324595]]
[[223.1585907 226.059922 ]]
[[-223.237

[[-293.48018499 -297.1686154 ]]
[[293.70173932 297.38529145]]
[[-293.7803686  -297.47212761]]
[[294.00192294 297.68880366]]
[[-294.08055221 -297.77563982]]
[[294.30210655 297.99231587]]
[[-294.38073582 -298.07915203]]
[[294.60229016 298.29582807]]
[[-294.68091944 -298.38266424]]
[[294.90247378 298.59934028]]
[[-294.98110305 -298.68617645]]
[[295.20265739 298.90285249]]
[[-295.28128666 -298.98968865]]
[[295.502841  299.2063647]]
[[-295.58147028 -299.29320086]]
[[295.80302462 299.50987691]]
[[-295.88165389 -299.59671307]]
[[296.10320823 299.81338912]]
[[-296.1818375  -299.90022528]]
[[296.40339184 300.11690133]]
[[-296.48202112 -300.20373749]]
[[296.70357546 300.42041354]]
[[-296.78220473 -300.5072497 ]]
[[297.00375907 300.72392574]]
[[-297.08238834 -300.81076191]]
[[297.30394268 301.02743795]]
[[-297.38257196 -301.11427412]]
[[297.60412629 301.33095016]]
[[-297.68275557 -301.41778632]]
[[297.90430991 301.63446237]]
[[-297.98293918 -301.72129853]]
[[298.20449352 301.93797458]]
[[-298.283

[[368.447459  372.9598314]]
[[-368.52608827 -373.04666756]]
[[368.74764261 373.26334361]]
[[-368.82627189 -373.35017977]]
[[369.04782622 373.56685582]]
[[-369.1264555  -373.65369198]]
[[369.34800984 373.87036803]]
[[-369.42663911 -373.95720419]]
[[369.64819345 374.17388023]]
[[-369.72682272 -374.2607164 ]]
[[369.94837706 374.47739244]]
[[-370.02700634 -374.5642286 ]]
[[370.24856068 374.78090465]]
[[-370.32718995 -374.86774081]]
[[370.54874429 375.08441686]]
[[-370.62737356 -375.17125302]]
[[370.8489279  375.38792907]]
[[-370.92755718 -375.47476523]]
[[371.14911152 375.69144128]]
[[-371.22774079 -375.77827744]]
[[371.44929513 375.99495349]]
[[-371.5279244  -376.08178965]]
[[371.74947874 376.29846569]]
[[-371.82810802 -376.38530186]]
[[372.04966236 376.6019779 ]]
[[-372.12829163 -376.68881406]]
[[372.34984597 376.90549011]]
[[-372.42847524 -376.99232627]]
[[372.65002958 377.20900232]]
[[-372.72865886 -377.29583848]]
[[372.9502132  377.51251453]]
[[-373.02884247 -377.59935069]]
[[373.2503

[[443.49336229 448.83788355]]
[[-443.57199157 -448.92471971]]
[[443.79354591 449.14139576]]
[[-443.87217518 -449.22823192]]
[[444.09372952 449.44490797]]
[[-444.17235879 -449.53174413]]
[[444.39391313 449.74842018]]
[[-444.47254241 -449.83525634]]
[[444.69409675 450.05193239]]
[[-444.77272602 -450.13876855]]
[[444.99428036 450.3554446 ]]
[[-445.07290963 -450.44228076]]
[[445.29446397 450.6589568 ]]
[[-445.37309325 -450.74579297]]
[[445.59464758 450.96246901]]
[[-445.67327686 -451.04930517]]
[[445.8948312  451.26598122]]
[[-445.97346047 -451.35281738]]
[[446.19501481 451.56949343]]
[[-446.27364409 -451.65632959]]
[[446.49519842 451.87300564]]
[[-446.5738277 -451.9598418]]
[[446.79538204 452.17651785]]
[[-446.87401131 -452.26335401]]
[[447.09556565 452.48003006]]
[[-447.17419492 -452.56686622]]
[[447.39574926 452.78354226]]
[[-447.47437854 -452.87037843]]
[[447.69593288 453.08705447]]
[[-447.77456215 -453.17389063]]
[[447.99611649 453.39056668]]
[[-448.07474576 -453.47740284]]
[[448.2963

[[-518.31771125 -524.49925966]]
[[518.53926559 524.71593571]]
[[-518.61789486 -524.80277187]]
[[518.8394492  525.01944791]]
[[-518.91807847 -525.10628408]]
[[519.13963281 525.32296012]]
[[-519.21826209 -525.40979628]]
[[519.43981643 525.62647233]]
[[-519.5184457  -525.71330849]]
[[519.74000004 525.92998454]]
[[-519.81862931 -526.0168207 ]]
[[520.04018365 526.23349675]]
[[-520.11881293 -526.32033291]]
[[520.34036727 526.53700896]]
[[-520.41899654 -526.62384512]]
[[520.64055088 526.84052117]]
[[-520.71918015 -526.92735733]]
[[520.94073449 527.14403337]]
[[-521.01936377 -527.23086954]]
[[521.24091811 527.44754558]]
[[-521.31954738 -527.53438174]]
[[521.54110172 527.75105779]]
[[-521.61973099 -527.83789395]]
[[521.84128533 528.05457   ]]
[[-521.91991461 -528.14140616]]
[[522.14146895 528.35808221]]
[[-522.22009822 -528.44491837]]
[[522.44165256 528.66159442]]
[[-522.52028183 -528.74843058]]
[[522.74183617 528.96510663]]
[[-522.82046545 -529.05194279]]
[[523.04201978 529.26861883]]
[[-523.1

[[-593.36361454 -600.37731181]]
[[593.58516888 600.59398786]]
[[-593.66379816 -600.68082402]]
[[593.88535249 600.89750007]]
[[-593.96398177 -600.98433623]]
[[594.18553611 601.20101228]]
[[-594.26416538 -601.28784844]]
[[594.48571972 601.50452448]]
[[-594.56434899 -601.59136065]]
[[594.78590333 601.80803669]]
[[-594.86453261 -601.89487285]]
[[595.08608695 602.1115489 ]]
[[-595.16471622 -602.19838506]]
[[595.38627056 602.41506111]]
[[-595.46489983 -602.50189727]]
[[595.68645417 602.71857332]]
[[-595.76508345 -602.80540948]]
[[595.98663779 603.02208553]]
[[-596.06526706 -603.10892169]]
[[596.2868214  603.32559774]]
[[-596.36545067 -603.4124339 ]]
[[596.58700501 603.62910994]]
[[-596.66563429 -603.71594611]]
[[596.88718863 603.93262215]]
[[-596.9658179  -604.01945831]]
[[597.18737224 604.23613436]]
[[-597.26600151 -604.32297052]]
[[597.48755585 604.53964657]]
[[-597.56618513 -604.62648273]]
[[597.78773947 604.84315878]]
[[-597.86636874 -604.92999494]]
[[598.08792308 605.14667099]]
[[-598.1

[[668.33088856 676.1685278 ]]
[[-668.40951784 -676.25536396]]
[[668.63107218 676.47204001]]
[[-668.70970145 -676.55887617]]
[[668.93125579 676.77555222]]
[[-669.00988506 -676.86238838]]
[[669.2314394  677.07906443]]
[[-669.31006868 -677.16590059]]
[[669.53162302 677.38257664]]
[[-669.61025229 -677.4694128 ]]
[[669.83180663 677.68608884]]
[[-669.9104359  -677.77292501]]
[[670.13199024 677.98960105]]
[[-670.21061952 -678.07643722]]
[[670.43217385 678.29311326]]
[[-670.51080313 -678.37994942]]
[[670.73235747 678.59662547]]
[[-670.81098674 -678.68346163]]
[[671.03254108 678.90013768]]
[[-671.11117035 -678.98697384]]
[[671.33272469 679.20364989]]
[[-671.41135397 -679.29048605]]
[[671.63290831 679.5071621 ]]
[[-671.71153758 -679.59399826]]
[[671.93309192 679.81067431]]
[[-672.01172119 -679.89751047]]
[[672.23327553 680.11418651]]
[[-672.31190481 -680.20102268]]
[[672.53345915 680.41769872]]
[[-672.61208842 -680.50453488]]
[[672.83364276 680.72121093]]
[[-672.91227203 -680.80804709]]
[[673.13

[[743.37679186 752.04657995]]
[[-743.45542113 -752.13341612]]
[[743.67697547 752.35009216]]
[[-743.75560474 -752.43692832]]
[[743.97715908 752.65360437]]
[[-744.05578836 -752.74044053]]
[[744.2773427  752.95711658]]
[[-744.35597197 -753.04395274]]
[[744.57752631 753.26062879]]
[[-744.65615558 -753.34746495]]
[[744.87770992 753.564141  ]]
[[-744.9563392  -753.65097716]]
[[745.17789354 753.86765321]]
[[-745.25652281 -753.95448937]]
[[745.47807715 754.17116541]]
[[-745.55670642 -754.25800158]]
[[745.77826076 754.47467762]]
[[-745.85689004 -754.56151379]]
[[746.07844438 754.77818983]]
[[-746.15707365 -754.86502599]]
[[746.37862799 755.08170204]]
[[-746.45725726 -755.1685382 ]]
[[746.6788116  755.38521425]]
[[-746.75744088 -755.47205041]]
[[746.97899521 755.68872646]]
[[-747.05762449 -755.77556262]]
[[747.27917883 755.99223867]]
[[-747.3578081  -756.07907483]]
[[747.57936244 756.29575088]]
[[-747.65799172 -756.38258704]]
[[747.87954605 756.59926308]]
[[-747.95817533 -756.68609925]]
[[748.17

[[-818.20114081 -827.70795606]]
[[818.42269515 827.92463211]]
[[-818.50132442 -828.01146827]]
[[818.72287876 828.22814432]]
[[-818.80150804 -828.31498048]]
[[819.02306238 828.53165652]]
[[-819.10169165 -828.61849269]]
[[819.32324599 828.83516873]]
[[-819.40187526 -828.92200489]]
[[819.6234296  829.13868094]]
[[-819.70205888 -829.2255171 ]]
[[819.92361322 829.44219315]]
[[-820.00224249 -829.52902931]]
[[820.22379683 829.74570536]]
[[-820.3024261  -829.83254152]]
[[820.52398044 830.04921757]]
[[-820.60260972 -830.13605373]]
[[820.82416406 830.35272978]]
[[-820.90279333 -830.43956594]]
[[821.12434767 830.65624198]]
[[-821.20297694 -830.74307815]]
[[821.42453128 830.95975419]]
[[-821.50316056 -831.04659036]]
[[821.7247149 831.2632664]]
[[-821.80334417 -831.35010256]]
[[822.02489851 831.56677861]]
[[-822.10352778 -831.65361477]]
[[822.32508212 831.87029082]]
[[-822.4037114  -831.95712698]]
[[822.62526574 832.17380303]]
[[-822.70389501 -832.26063919]]
[[822.92544935 832.47731524]]
[[-823.004

[[-893.24704411 -903.58600821]]
[[893.46859845 903.80268426]]
[[-893.54722772 -903.88952042]]
[[893.76878206 904.10619647]]
[[-893.84741133 -904.19303263]]
[[894.06896567 904.40970868]]
[[-894.14759495 -904.49654484]]
[[894.36914928 904.71322089]]
[[-894.44777856 -904.80005705]]
[[894.6693329  905.01673309]]
[[-894.74796217 -905.10356926]]
[[894.96951651 905.3202453 ]]
[[-895.04814579 -905.40708146]]
[[895.26970012 905.62375751]]
[[-895.3483294  -905.71059367]]
[[895.56988374 905.92726972]]
[[-895.64851301 -906.01410588]]
[[895.87006735 906.23078193]]
[[-895.94869662 -906.31761809]]
[[896.17025096 906.53429414]]
[[-896.24888024 -906.6211303 ]]
[[896.47043458 906.83780635]]
[[-896.54906385 -906.92464251]]
[[896.77061819 907.14131855]]
[[-896.84924746 -907.22815472]]
[[897.0708018  907.44483076]]
[[-897.14943108 -907.53166693]]
[[897.37098542 907.74834297]]
[[-897.44961469 -907.83517913]]
[[897.67116903 908.05185518]]
[[-897.7497983  -908.13869134]]
[[897.97135264 908.35536739]]
[[-898.0

[[968.21431813 979.3772242 ]]
[[-968.2929474  -979.46406037]]
[[968.51450174 979.68073641]]
[[-968.59313101 -979.76757257]]
[[968.81468535 979.98424862]]
[[-968.89331463 -980.07108478]]
[[969.11486897 980.28776083]]
[[-969.19349824 -980.37459699]]
[[969.41505258 980.59127304]]
[[-969.49368185 -980.6781092 ]]
[[969.71523619 980.89478525]]
[[-969.79386547 -980.98162141]]
[[970.01541981 981.19829746]]
[[-970.09404908 -981.28513362]]
[[970.31560342 981.50180966]]
[[-970.39423269 -981.58864583]]
[[970.61578703 981.80532187]]
[[-970.69441631 -981.89215803]]
[[970.91597065 982.10883408]]
[[-970.99459992 -982.19567024]]
[[971.21615426 982.41234629]]
[[-971.29478353 -982.49918245]]
[[971.51633787 982.7158585 ]]
[[-971.59496715 -982.80269466]]
[[971.81652148 983.01937071]]
[[-971.89515076 -983.10620687]]
[[972.1167051  983.32288292]]
[[-972.19533437 -983.40971908]]
[[972.41688871 983.62639512]]
[[-972.49551798 -983.71323129]]
[[972.71707232 983.92990733]]
[[-972.7957016  -984.01674349]]
[[973.01

[[1043.26022142 1055.25527636]]
[[-1043.33885069 -1055.34211252]]
[[1043.56040503 1055.55878857]]
[[-1043.63903431 -1055.64562473]]
[[1043.86058865 1055.86230077]]
[[-1043.93921792 -1055.94913694]]
[[1044.16077226 1056.16581298]]
[[-1044.23940153 -1056.25264914]]
[[1044.46095587 1056.46932519]]
[[-1044.53958515 -1056.55616135]]
[[1044.76113949 1056.7728374 ]]
[[-1044.83976876 -1056.85967356]]
[[1045.0613231  1057.07634961]]
[[-1045.13995237 -1057.16318577]]
[[1045.36150671 1057.37986182]]
[[-1045.44013599 -1057.46669798]]
[[1045.66169033 1057.68337403]]
[[-1045.7403196  -1057.77021019]]
[[1045.96187394 1057.98688623]]
[[-1046.04050321 -1058.0737224 ]]
[[1046.26205755 1058.29039844]]
[[-1046.34068683 -1058.3772346 ]]
[[1046.56224117 1058.59391065]]
[[-1046.64087044 -1058.68074681]]
[[1046.86242478 1058.89742286]]
[[-1046.94105405 -1058.98425902]]
[[1047.16260839 1059.20093507]]
[[-1047.24123767 -1059.28777123]]
[[1047.46279201 1059.50444728]]
[[-1047.54142128 -1059.59128344]]
[[1047.762

[[-1118.08457038 -1130.91665246]]
[[1118.30612472 1131.13332851]]
[[-1118.38475399 -1131.22016467]]
[[1118.60630833 1131.43684072]]
[[-1118.6849376  -1131.52367688]]
[[1118.90649194 1131.74035293]]
[[-1118.98512122 -1131.82718909]]
[[1119.20667555 1132.04386514]]
[[-1119.28530483 -1132.1307013 ]]
[[1119.50685917 1132.34737734]]
[[-1119.58548844 -1132.43421351]]
[[1119.80704278 1132.65088955]]
[[-1119.88567205 -1132.73772571]]
[[1120.10722639 1132.95440176]]
[[-1120.18585567 -1133.04123792]]
[[1120.40741001 1133.25791397]]
[[-1120.48603928 -1133.34475013]]
[[1120.70759362 1133.56142618]]
[[-1120.78622289 -1133.64826234]]
[[1121.00777723 1133.86493839]]
[[-1121.08640651 -1133.95177455]]
[[1121.30796085 1134.1684506 ]]
[[-1121.38659012 -1134.25528676]]
[[1121.60814446 1134.4719628 ]]
[[-1121.68677373 -1134.55879897]]
[[1121.90832807 1134.77547501]]
[[-1121.98695735 -1134.86231117]]
[[1122.20851169 1135.07898722]]
[[-1122.28714096 -1135.16582338]]
[[1122.5086953  1135.38249943]]
[[-1122.58

[[-1193.13047367 -1206.79470462]]
[[1193.35202801 1207.01138066]]
[[-1193.43065728 -1207.09821682]]
[[1193.65221162 1207.31489287]]
[[-1193.7308409  -1207.40172903]]
[[1193.95239524 1207.61840508]]
[[-1194.03102451 -1207.70524124]]
[[1194.25257885 1207.92191729]]
[[-1194.33120812 -1208.00875345]]
[[1194.55276246 1208.2254295 ]]
[[-1194.63139174 -1208.31226566]]
[[1194.85294608 1208.52894171]]
[[-1194.93157535 -1208.61577787]]
[[1195.15312969 1208.83245391]]
[[-1195.23175896 -1208.91929008]]
[[1195.4533133  1209.13596612]]
[[-1195.53194258 -1209.22280228]]
[[1195.75349691 1209.43947833]]
[[-1195.83212619 -1209.52631449]]
[[1196.05368053 1209.74299054]]
[[-1196.1323098 -1209.8298267]]
[[1196.35386414 1210.04650275]]
[[-1196.43249341 -1210.13333891]]
[[1196.65404775 1210.35001496]]
[[-1196.73267703 -1210.43685112]]
[[1196.95423137 1210.65352717]]
[[-1197.03286064 -1210.74036333]]
[[1197.25441498 1210.95703937]]
[[-1197.33304425 -1211.04387554]]
[[1197.55459859 1211.26055158]]
[[-1197.6332

[[1268.09774769 1282.58592061]]
[[-1268.17637696 -1282.67275677]]
[[1268.3979313  1282.88943281]]
[[-1268.47656058 -1282.97626898]]
[[1268.69811492 1283.19294502]]
[[-1268.77674419 -1283.27978119]]
[[1268.99829853 1283.49645723]]
[[-1269.0769278  -1283.58329339]]
[[1269.29848214 1283.79996944]]
[[-1269.37711142 -1283.8868056 ]]
[[1269.59866576 1284.10348165]]
[[-1269.67729503 -1284.19031781]]
[[1269.89884937 1284.40699386]]
[[-1269.97747864 -1284.49383002]]
[[1270.19903298 1284.71050607]]
[[-1270.27766226 -1284.79734223]]
[[1270.4992166  1285.01401828]]
[[-1270.57784587 -1285.10085444]]
[[1270.79940021 1285.31753048]]
[[-1270.87802948 -1285.40436665]]
[[1271.09958382 1285.62104269]]
[[-1271.1782131  -1285.70787885]]
[[1271.39976744 1285.9245549 ]]
[[-1271.47839671 -1286.01139106]]
[[1271.69995105 1286.22806711]]
[[-1271.77858032 -1286.31490327]]
[[1272.00013466 1286.53157932]]
[[-1272.07876394 -1286.61841548]]
[[1272.30031827 1286.83509153]]
[[-1272.37894755 -1286.92192769]]
[[1272.600

[[1343.14365098 1358.46397276]]
[[-1343.22228026 -1358.55080892]]
[[1343.4438346  1358.76748497]]
[[-1343.52246387 -1358.85432113]]
[[1343.74401821 1359.07099718]]
[[-1343.82264748 -1359.15783334]]
[[1344.04420182 1359.37450938]]
[[-1344.1228311  -1359.46134555]]
[[1344.34438544 1359.67802159]]
[[-1344.42301471 -1359.76485776]]
[[1344.64456905 1359.9815338 ]]
[[-1344.72319832 -1360.06836996]]
[[1344.94475266 1360.28504601]]
[[-1345.02338194 -1360.37188217]]
[[1345.24493628 1360.58855822]]
[[-1345.32356555 -1360.67539438]]
[[1345.54511989 1360.89207043]]
[[-1345.62374916 -1360.97890659]]
[[1345.8453035  1361.19558264]]
[[-1345.92393278 -1361.2824188 ]]
[[1346.14548712 1361.49909484]]
[[-1346.22411639 -1361.58593101]]
[[1346.44567073 1361.80260705]]
[[-1346.5243     -1361.88944322]]
[[1346.74585434 1362.10611926]]
[[-1346.82448362 -1362.19295542]]
[[1347.04603796 1362.40963147]]
[[-1347.12466723 -1362.49646763]]
[[1347.34622157 1362.71314368]]
[[-1347.42485084 -1362.79997984]]
[[1347.646

[[-1417.96799994 -1434.12534886]]
[[1418.18955428 1434.34202491]]
[[-1418.26818355 -1434.42886107]]
[[1418.48973789 1434.64553712]]
[[-1418.56836717 -1434.73237328]]
[[1418.78992151 1434.94904933]]
[[-1418.86855078 -1435.03588549]]
[[1419.09010512 1435.25256154]]
[[-1419.16873439 -1435.3393977 ]]
[[1419.39028873 1435.55607375]]
[[-1419.46891801 -1435.64290991]]
[[1419.69047234 1435.85958595]]
[[-1419.76910162 -1435.94642212]]
[[1419.99065596 1436.16309816]]
[[-1420.06928523 -1436.24993432]]
[[1420.29083957 1436.46661037]]
[[-1420.36946885 -1436.55344653]]
[[1420.59102318 1436.77012258]]
[[-1420.66965246 -1436.85695874]]
[[1420.8912068  1437.07363479]]
[[-1420.96983607 -1437.16047095]]
[[1421.19139041 1437.377147  ]]
[[-1421.27001968 -1437.46398316]]
[[1421.49157402 1437.68065921]]
[[-1421.5702033  -1437.76749537]]
[[1421.79175764 1437.98417141]]
[[-1421.87038691 -1438.07100758]]
[[1422.09194125 1438.28768362]]
[[-1422.17057052 -1438.37451979]]
[[1422.39212486 1438.59119583]]
[[-1422.47

[[-1493.01390323 -1510.00340102]]
[[1493.23545757 1510.22007706]]
[[-1493.31408685 -1510.30691323]]
[[1493.53564119 1510.52358927]]
[[-1493.61427046 -1510.61042543]]
[[1493.8358248  1510.82710148]]
[[-1493.91445407 -1510.91393764]]
[[1494.13600841 1511.13061369]]
[[-1494.21463769 -1511.21744985]]
[[1494.43619203 1511.4341259 ]]
[[-1494.5148213  -1511.52096206]]
[[1494.73637564 1511.73763811]]
[[-1494.81500491 -1511.82447427]]
[[1495.03655925 1512.04115032]]
[[-1495.11518853 -1512.12798648]]
[[1495.33674287 1512.34466252]]
[[-1495.41537214 -1512.43149869]]
[[1495.63692648 1512.64817473]]
[[-1495.71555575 -1512.73501089]]
[[1495.93711009 1512.95168694]]
[[-1496.01573937 -1513.0385231 ]]
[[1496.23729371 1513.25519915]]
[[-1496.31592298 -1513.34203531]]
[[1496.53747732 1513.55871136]]
[[-1496.61610659 -1513.64554752]]
[[1496.83766093 1513.86222357]]
[[-1496.91629021 -1513.94905973]]
[[1497.13784454 1514.16573578]]
[[-1497.21647382 -1514.25257194]]
[[1497.43802816 1514.46924798]]
[[-1497.51

In [144]:
w = pd.DataFrame({0: [0.], 1: [0.]}).values

for i in range(10000):
    print (w)
    delta = delta_w(w, k=0.05)
    w += delta
    if np.linalg.norm(delta) < 10**(-5):
        print (w)
        break
w_reg = w

[[0. 0.]]
[[0.01786563 0.01622999]]
[[0.02448157 0.02184589]]
[[0.02697951 0.02379103]]
[[0.02793787 0.0244581 ]]
[[0.0283109 0.0246817]]
[[0.0284583  0.02475374]]
[[0.02851751 0.02477538]]
[[0.02854172 0.02478101]]
[[0.0285518  0.02478196]]
[[0.02855609 0.02478178]]


# 7. Попробуйте менять начальное приближение. Влияет ли оно на что-нибудь?

In [145]:
w = pd.DataFrame({0: [-10.0], 1: [-10.0]}).values

for i in range(10000):
    print (w)
    delta = delta_w(w)
    w += delta
    if np.linalg.norm(delta) < 10**(-5):
        print (w)
        break
w_reg = w

[[-10. -10.]]
[[0.11045104 0.10850708]]
[[0.01212333 0.00749141]]
[[0.03300811 0.02965127]]
[[0.02738488 0.02349603]]
[[0.02887388 0.02512547]]
[[0.02847548 0.0246889 ]]
[[0.02858186 0.02480546]]
[[0.02855344 0.02477431]]
[[0.02856103 0.02478263]]
[[0.028559   0.02478041]]
